name: test churros
on: push
jobs:
  build-hs:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        ghc:
          - version: "9.2.4"
            action: |
              echo "/opt/ghc/9.2.4/bin" >> $GITHUB_PATH
        cabal:
          - version: "3.2.0.0"
            action: |
              echo "/opt/cabal/3.2/bin" >> $GITHUB_PATH


    runs-on: ${{ matrix.os }} 

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{matrix.ghc.version}}
          cabal-version: ${{matrix.cabal.version}}

      - run: cabal build
      - run: cabal exec cabal test
